config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'chat_messages/show'
  end
  # エンドユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/homes#top'

  # 管理者用
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :news, only: [:new, :show, :index, :create]
    resources :golf_spots, only: [:index, :create, :edit, :update]
  end

  # エンドユーザー用
  # scope module: :public publicをpath名から消す
  scope module: :public do
    get 'about' => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      # 基本の7種のアクション以外を定義する時にmember doやcollection doを利用する
      member do
        get :likes
      end
      collection do
        get :unsubscribe
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      # get "unsubscribe" => "users#unsubscribe"
      # patch "withdraw" => "users#withdraw"
      
    end

    resources :searches, only: [:index]

    resources :golf_spot_searches, only: [:index, :show]



    get 'chat_message/:id' => 'chat_messages#show', as: 'chat_message'
    resources :chat_messages, only: [:create]

    resources :chat_rooms, only: [:show, :index] do
      resources :chat_messages, only: [:create]
    end

    resources :rankings, only: [:show]

    resources :golf_spots, only: [:index, :show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/golf_spot.rb
class GolfSpot < ApplicationRecord
  has_many :posts
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @golf_spot = GolfSpot.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @golf_spot = GolfSpot.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @golf_spot = GolfSpot.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @golf_spot = GolfSpot.where("name LIKE?","%#{word}%")
    else
      @golf_spot = GolfSpot.all
    end
  end
end

app/controllers/admin/golf_spots_controller.rb
class Admin::GolfSpotsController < ApplicationController
  def index
    @golf_spot = GolfSpot.new
    @golf_spots = GolfSpot.all
  end
  
  def create
    @golf_spot = GolfSpot.new(golf_spot_params)
    @golf_spot.save
    redirect_to admin_golf_spots_path
  end

  def edit
    @golf_spot = GolfSpot.find(params[:id])
  end
  
  def update
    @golf_spot = GolfSpot.find(params[:id])
    @golf_spot.update(golf_spot_params)
    redirect_to admin_golf_spots_path
  end
  
  private
  def golf_spot_params
    params.require(:golf_spot).permit(:name)
  end
end

app/helpers/admin/golf_spots_helper.rb
module Admin::GolfSpotsHelper
end

app/views/admin/golf_spots/edit.html.erb
<div class="container pt-5 px-sm-0">
  <div class="row">
    <h3 class="title">ゴルフ場編集</h3>
  </div>
  <div class="mt-5">
    <%= form_with model: [:admin, @golf_spot], local: true do |f| %>
      <div class ="row">
        <div class="col-md-3 text-center">ゴルフ場名</div>
        <div class="col-md-3 text-center">
          <%= f.text_field :name, autocomplete: "name", class:"form-control", placeholder: 'ゴルフ場名' %>
        </div>
        <div class="col-md-3 text-center">
          <%= f.submit '変更を保存', class: "btn btn-sm btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/golf_spots/index.html.erb
<div class="container pt-5">
  <div class="row">
    <h3 class="title" style="background-color: #eee;">ゴルフ場一覧・追加</h3>
  </div>
  <div class="mt-5">
    <%= form_with model: [:admin, @golf_spot], local: true do |f| %>
    <div class ="row">
      <div class="col-md-2 text-center">ゴルフ場名</div>
        <div class="col-md-3">
          <%= f.text_field :name, autocomplete: "name", class:"form-control", placeholder: 'ゴルフ場名' %>
        </div>
        <div>
          <%= f.submit '新規登録', class: "btn btn-lg btn-success btn-inline ml-5" %>
        </div>
    </div>
    <% end %>
  </div>
  <div class="row mt-5">
    <div class="col-md-5">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ゴルフ場</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @golf_spots.each do |golf_spot| %>
            <tr>
              <td class=""><%= golf_spot.name %></td>
              <td class="text-center"><%= link_to '   編集する  ', edit_admin_golf_spot_path(golf_spot.id), class: "btn btn-sm btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>