config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'chat_messages/show'
  end
  # エンドユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/homes#top'

  # 管理者用
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :news, only: [:new, :show, :index, :create]
    resources :golf_spots, only: [:index, :create, :edit, :update]
  end

  # エンドユーザー用
  # scope module: :public publicをpath名から消す
  scope module: :public do
    get 'about' => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      # 基本の7種のアクション以外を定義する時にmember doやcollection doを利用する
      member do
        get :likes
      end
      collection do
        get :unsubscribe
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      # get "unsubscribe" => "users#unsubscribe"
      # patch "withdraw" => "users#withdraw"
      
    end

    resources :searches, only: [:index]

    resources :golf_spot_searches, only: [:index, :show]



    get 'chat_message/:id' => 'chat_messages#show', as: 'chat_message'
    resources :chat_messages, only: [:create]

    resources :chat_rooms, only: [:show, :index] do
      resources :chat_messages, only: [:create]
    end

    resources :rankings, only: [:show]

    resources :golf_spots, only: [:index, :show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  # 投稿との関係
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :liked_posts, through: :likes, source: :post

  # チャットルームとの関係
  has_many :chat_members
  has_many :chat_rooms, through: :chat_members
  has_many :chat_messages, dependent: :destroy

  # フォローした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # タグとの関係
  has_many :user_tags, dependent: :destroy
  has_many :tags, through: :user_tags

  validates :name, length: { minimum: 1, maximum: 10 }, uniqueness: true

  validates :introduction, length: { maximum: 50 }

  enum gender: { man: 0, woman: 1}
  enum area: { "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47 }

  def self.guest
    find_or_create_by!(name: 'guestuser', gender: "man",age: 10,area: 1, email: 'guest@example.com', is_deleted: false) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @user = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :gender, :age, :area, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-8'>
      <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
        <h3 class="m-0">
          <%= @user.name %>さんのユーザー情報編集
        </h3>
      </div>

      <%= form_with model: @user, url: admin_user_path(@user), local:true, method: :patch do |f| %>
      <table class="table table-borderless table-sm">
        <div class="field">
          <tr>
            <td><%= f.label :"ユーザーID" %></td>
            <td colspan='2' class="pl-5"><%= @user.id %></td>
          </tr>
        </div>
        
        <div class="field">
          <tr>
            <td><%= f.label :"性別" %></td>
            <td><%= f.label :gender, User.genders_i18n[:man], style: "margin-left:40px;" %>
                <%= f.radio_button :gender, User.genders.key(0) %>
                <%= f.label :gender, User.genders_i18n[:woman] %>
                <%= f.radio_button :gender, User.genders.key(1) %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
            <td><%= f.label :"年齢" %></td>
            <td><%= f.select :age, {"10代": 10, "20代": 20, "30代": 30, "40代": 40, "50代": 50, "60代": 60, "70代": 70, "80代": 80 }, {}, style: "margin-left:40px;" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"都道府県" %></td>
          <td><%= f.select :area, User.areas.keys, {}, style: "margin-left:40px;" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email, style: "margin-left:40px;",autocomplete: "email" %></td>
          </tr>
        </div>

        <div class="actions">
          <tr>
          <td>会員ステータス</td>
        　<td>
          　<%= f.radio_button :is_deleted, false, style: "margin-left:40px;" %>
            <%= f.label :is_deleted, "有効", value: :false %>
            <%= f.radio_button :is_deleted, true %>
          　<%= f.label :is_deleted, "退会", value: :true %>
          </td>
          </tr>
        </div>
      <div class="actions">
        <tr>
        <td><br><%= f.submit '変更を保持', class: 'btn btn-success' %></td></tr>
      </div>
    <% end %>
  </table>

app/views/admin/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
      <h2 class="m-0">ユーザー一覧</h2>
    </div>

    <table class="table table">
      <thead>
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
          <th>性別</th>
          <th>年齢</th>
          <th>都道府県</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @user.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <%= link_to admin_user_path(user), style: "text-decoration: underline;" do%>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.gender_i18n %></td>
            <td><%= user.age %>代</td>
            <td><%= user.area %></td>
            <td><%= user.email %></td>

            <% if user.is_deleted == false %>
      　　　　　　<td class = "text-success font-weight-bold">有効</td>
        	  　<%else%>
      　　　　　　<td class = "text-secondary font-weight-bold">退会</td>
        	  <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row justify-content-center">
      <%= paginate @user %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-8'>
      <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
        <h3 class="m-0">
          <%= @user.name %>さんの会員詳細
        </h3>
      </div>

      <table class="table table-borderless">
      <tr>
        <td>会員ID</td>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <td>ユーザー名</td>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <td>性別</td>
        <td><%= @user.gender_i18n %></td>
      </tr>
       <tr>
        <td>年齢</td>
        <td><%= @user.age %>代</td>
      </tr>
      <tr>
        <td>都道府県</td>
        <td><%= @user.area %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td colspan='2'>
          <% if @user.is_deleted == true %>
          <div class="text-secondary font-weight-bold">退会</div>
          <% else %>
          <div class="text-success font-weight-bold">有効</div>
          <% end %>
          </td>
      </tr>
        <tfoot>
          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_user_path,class: "btn btn-success" %></td>
          </tr>
        </tfoot>
    </table>
  </div>
 </div>
</div>