config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'chat_messages/show'
  end
  # エンドユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  root 'public/homes#top'

  # 管理者用
  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update]
    resources :news, only: [:new, :show, :index, :create]
    resources :golf_spots, only: [:index, :create, :edit, :update]
  end

  # エンドユーザー用
  # scope module: :public publicをpath名から消す
  scope module: :public do
    get 'about' => "homes#about", as: 'about'

    resources :posts, only: [:new, :index, :show, :create, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      # 基本の7種のアクション以外を定義する時にmember doやcollection doを利用する
      member do
        get :likes
      end
      collection do
        get :unsubscribe
        patch :withdraw
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      # get "unsubscribe" => "users#unsubscribe"
      # patch "withdraw" => "users#withdraw"
      
    end

    resources :searches, only: [:index]

    resources :golf_spot_searches, only: [:index, :show]



    get 'chat_message/:id' => 'chat_messages#show', as: 'chat_message'
    resources :chat_messages, only: [:create]

    resources :chat_rooms, only: [:show, :index] do
      resources :chat_messages, only: [:create]
    end

    resources :rankings, only: [:show]

    resources :golf_spots, only: [:index, :show]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoflFriend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダー-->
    <header class="sticky-top", style="background-color: #D0F5E1">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar text-center" href="/"><h2 class="text-center"><strong>GolfFriend</strong></h2></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse row" id="navbarNavDropdown">


            <!--エンドユーザー用ヘッダー-->
            <% if user_signed_in? %>
            <h5 class="mr-5">ようこそ、<%= current_user.name %>さん!</h5>
              <ul class="navbar-nav ml-auto">
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
                <% if current_user.name != "guestuser" %>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "マイページ", "/users/#{current_user.id}", class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "投稿する", new_post_path, class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "チャット一覧", chat_rooms_path, class: 'nav-link text-dark' %></li>
                <% end %>
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </ul>

            <!--管理者用ヘッダー-->
            <% elsif admin_signed_in?  %>
              <ul class="navbar-nav ml-auto">
                <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark'%></li>
                <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "お知らせ投稿", new_admin_news_path, class: 'nav-link text-dark'%></li>
                <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "ゴルフ場追加", admin_golf_spots_path, class: 'nav-link text-dark'%></li>
                <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark'%></li>
              </ul>

            <!--ログイン前ヘッダー-->
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "About", about_path, class: 'nav-link text-dark'%></li>
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %></li>
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %></li>
                <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "ゲストログイン(閲覧用)", users_guest_sign_in_path, class: 'nav-link text-dark', method: :post %></li>
              </ul>
            <% end %>

            <!--投稿検索フォーム-->
            <div class="container justify-content-end pt-3">
              <div class="row">
                <div class="col-ml-auto mr-4">
                  <%= render 'public/searches/form' %>
                </div>
              </div>
            </div>
            <!--検索フォームここまで-->
          </div>
        </div>
      </nav>
    </header>

    <!--ヘッダーと被らないようにする-->
    <body style="padding-bottom:4rem"></body>

    <%= yield %>

    <!--フッター-->
    <footer class="fixed-bottom" style="background-color: #D0F5E1">
      <div style="padding: 5px;">
        <h6 class="text-dark text-center mr-3" id="footer_logo"><small>©GolfFriend</small></h6>
      </div>
    </footer>
  </body>
</html>